version: '2'

services:
    server1:
        build: docker/php7-fpm1
        env_file: .env
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/${PROJECT_NAME}1:cached
            - ${SYMFONY_APP_PATH}/var/log:/var/www/${PROJECT_NAME}1/var/logs:cached
    server2:
        build: docker/php7-fpm2
        env_file: .env
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/${PROJECT_NAME}2:cached
            - ${SYMFONY_APP_PATH}/var/log:/var/www/${PROJECT_NAME}2/var/logs:cached
    nginx1:
        build: docker/nginx1
        ports:
            - ${NGINX1_PORT}:80
        volumes:
            - ./var/log:/var/log/nginx2:cached
        volumes_from:
            - server1
    nginx2:
        build: docker/nginx2
        ports:
            - ${NGINX2_PORT}:80
        volumes:
            - ./var/log:/var/log/nginx2:cached
        volumes_from:
            - server2
#    centralized_server: ~
    elk:
        image: willdurand/elk
        ports:
            - ${ELK_PORT}:80
            - ${LOGSTASH_PORT}:9200
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - cne
#            - nginx
